name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build - ${{ matrix.configuration }}
  
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6
          7
          9
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}

    - name: Test
      if: matrix.configuration == 'Debug'
      run: dotnet test --no-build
