name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build - ${{ matrix.configuration }}

    strategy:
      matrix:
        configuration: [ Debug, Release ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Mono
      run: sudo apt-get update && sudo apt-get install -y mono-runtime

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            8.0.x
            6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Debug NuGet Packages Path
      run: dotnet nuget locals global-packages -l

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}

    - name: Test
      if: matrix.configuration == 'Debug'
      run: dotnet test --no-build

    - name: Upload packages
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: /home/runner/work/Blazor.Diagrams/Blazor.Diagrams/src/Blazor.Diagrams/bin/Release/*.nupkg
        retention-days: 5
